### ISSUE TITLE
Add addin to website to allow for automatic documentation

### ISSUE THREAD

**Issue by gep13** [RadioSystems/Cake.Orchard#2]
i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#152

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by gep13** [comment]
@phillipsj just wanted to touch base to see if you had thought about doing this. Thanks!

**Comment by phillipsj** [comment]
@gep13 Thanks, for reminding me. I have added the documentation and submitted a pull request to the website.  I am going to close this issue.

**Comment by gep13** [comment]
Nice one! Thank you!
